### ISSUE TITLE
有使用的ｅｘａｍｐｌｅ吗，可以帮助入门

### ISSUE THREAD

**Issue by jiashiwen** [jdcloud-api/jdcloud-sdk-net#1]

**Comment by shijunLee** [comment]
在代码的sdk/src/Examples 目录下有相关的测试example，其中standard2 下有较为详细的调用用例，推荐使用.NET 4.5 以上版本的.NET Framework，需要在京东云官网登陆并获取 accessKeyId 和
 secretAccessKey  然后使用本api，具体的资源和调用api 请查看[OpenAPI&SDK](https://www.jdcloud.com/help/faq?act=3)
